In [1]:
import pandas as pd

In [3]:
demographics_data=pd.read_excel(r'G:\IDM PROJECT\THE DATA\demographic.xlsx')
diet_data=pd.read_excel(r'G:\IDM PROJECT\THE DATA\diet.xlsx')
examination_data=pd.read_excel(r'G:\IDM PROJECT\THE DATA\examination.xlsx')
labs_data=pd.read_excel(r'G:\IDM PROJECT\THE DATA\labs.xlsx')
medications_data=pd.read_excel(r'G:\IDM PROJECT\THE DATA\medications.xlsx')
questionaire_data=pd.read_excel(r'G:\IDM PROJECT\THE DATA\questionnaire.xlsx')

diet_data.head()

,SEQN,WTDRD1,WTDR2D,DR1DRSTZ,DR1EXMER,DRABF,DRDINT,DR1DBIH,DR1DAY,DR1LANG,...,DRD370QQ,DRD370R,DRD370RQ,DRD370S,DRD370SQ,DRD370T,DRD370TQ,DRD370U,DRD370UQ,DRD370V
0,73557.0,16888.327864,12930.890649,1.0,49.0,2.0,2.0,6.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,73558.0,17932.143865,12684.148869,1.0,59.0,2.0,2.0,4.0,1.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0
2,73559.0,59641.812930,39394.236709,1.0,49.0,2.0,2.0,18.0,6.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,73560.0,142203.069917,125966.366442,1.0,54.0,2.0,2.0,21.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,73561.0,59052.357033,39004.892993,1.0,63.0,2.0,2.0,18.0,1.0,1.0,...,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0